### ISSUE TITLE
Fails if .env file has an env variable with a space in it.

### ISSUE THREAD

**Issue by gilescope** [lirsacc/dotenv-exec#1]
Failed to load default env file: Error parsing line: '.../usr/local/git/bin:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin', error at line index: 652

It didn't like /Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin being in the PATH which I can onlly assume is because there's a space in it. I think spaces should be valid in .env files?

**Comment by gilescope** [comment]
(Thank you for coding this btw. I'm finding this useful command with my 'env-min' tool: https://github.com/gilescope/env_min )

**Comment by lirsacc** [comment]
Hey @gilescope sorry for the delay here I completely missed that issue :(

This seems to be a problem in the [dotenv crate](https://github.com/dotenv-rs/dotenv) (I could reproduce this when just using `dotenv::dotenv().unwrap();`) which is used internally to load the .env files. 

It works when quoted, but I agree that in general this should be fine for unquoted values as long there isn't a newline. I won't have time for a couple weeks but, once I've been able to look into it in more details I would likely open an issue or PR against the dotenv crate.

In the meantime, I reckon quoting the value should work, so you could do `PATH="... PATH WITH SPACE ..."` or if your use case involves extracting values, you could do `PATH=\"${PATH}\"` which will add quotes around the existing env variable.
